version: 0.0
os: linux
files:
  - source: /
    destination: /opt/discovery-service
permissions:
  - object: /opt/discovery-service/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStop:
    - location: kill_process.sh
  ApplicationStart:
    - location: run_java.sh
